name: kinase
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.11.26=hca03da5_0
  - expat=2.6.4=h313beb8_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.15=h80987f9_0
  - pip=24.2=py312hca03da5_0
  - python=3.12.8=h99e199e_0
  - readline=8.2=h1a28f6b_0
  - setuptools=75.1.0=py312hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - wheel=0.44.0=py312hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - anyio==4.7.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==24.3.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - debugpy==1.8.11
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.31.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==2.2.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - torch==2.5.1
      - torch-cluster==1.6.3
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - yarl==1.18.3
prefix: /opt/anaconda3/envs/kinase
